# -*- coding: utf-8 -*-
"""IMC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1np_Hfs1b6lCCspqjkahLoRkWOvnFLgrn
"""

altura = float (input('Entre com sua altura atual: '))
peso = float(input('Entre com seu peso atual: '))
IMC = peso/(altura**2)
print("Seu IMC é: %.2f" % IMC)

if IMC <= 18.5:
  print('Você esta abaixo do peso')
elif IMC <= 25:
  print('Parabens!! Você esta na média!!')
elif IMC <= 35:
  print('Cuidado, você esta acima do peso!!')
else:
  print('Voê entrou no status Obesidade, risco de vida. Procure seu médico com urgencia')